### ISSUE TITLE
Endre rekkefølge på heat i kjøreplan / redigere et enkelt heat (inkludert slette).

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service-gui#117]
Løst ved å gi mulighet for manuelt å sette tidspunkt for heatet. Kan også endre maks antall deltakere.

Denne må løses på en annen måte!

**Comment by stigbd** [comment]
Eit par kommentarer til dette issuet/commiten:
- Eg forstod ikkje heilt korleis dette issuet relaterer til å slette heat.
- I koden gjer vi no get_all_races og looper til vi finner korrekt race, hadde det ikkje vore enklare/raskare å gjere get_race_by_id direkte? Ref https://github.com/langrenn-sprint/event-service-gui/blob/6c2c12102f04f300ef5a239530b53f3bbd5f3cbf/event_service_gui/views/raceplans.py#L125-L127

**Comment by stigbd** [comment]
Forstår. Dette er nok ein bug i backend.
