### ISSUE TITLE
Ved sletting av valge deltakere, blir kun 1 slettet.

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service-gui#143]
Feilmelding vises også selv om sletting ser ut til å ha funnet sted.

**Comment by heming-langrenn** [comment]
Dette er en bug som oppstår når deltaker slettes før startnummer er tildelt. Årsak er at startnummer brukes som nøkkel for å finne contestant_id i form som sendes til server. Endrer nøkkel til et løpenummer.
