### ISSUE TITLE
Ved justering av kjøreplan, gis det ingen feil eller warning når negativt tidsintervall oppstår

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service-gui#144]
Ved justering av starttider på eitt og eitt heat, vart det lagt inn starttid som var før heatet som starta før. 
Feilen vart oppdaga av oss, men en warning eller feilmelding var forventa.

Sjå screenshot:
![Screenshot from 2024-01-04 21-22-39](https://github.com/langrenn-sprint/event-service-gui/assets/1702357/e4668fac-f30a-46d1-992a-55d2136d076c)

**Comment by stigbd** [comment]
Når brukar går tilbake til admin-sida "Sette rennet", får brukar opp ein advarsel om at Kjøreplan er ukronologisk. Dette er antagelegvis godt nok.

**Comment by heming-langrenn** [comment]
Enig i at dette er en "feature". Front-end bør tillate dette, men valideringen gjør at man kan sjekke. I noen tilfeller kan det kanskje være ønskelig å stokke litt om på start-tidene.
