### ISSUE TITLE
Oppdatere "startrekkefølge" feiler med "Det har oppstått en feil - ('Error - 422: Mandatory property ageclasses is missing..',)."

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service-gui#62]
Gjenskape:
1. Opprett klasser - legge inn startgruppe og startrekkefølge
2. Trykk "Rediger" og trykk "Rediger" på en klasse,
3. Endre startrekkefølge-verdi og trykk "Oppdater"

Ref skjermdump:
![image](https://user-images.githubusercontent.com/1702357/151866826-f7bfa612-3b5f-49ee-9b22-e2198ac3b98c.png)

**Comment by heming-langrenn** [comment]
Fikset - mer at denne foreløpig bare støtter en ageclass pr raceclass.
