### ISSUE TITLE
[Skjermflyt] Hopper til hovedmeny etter å ha trykt på "Generer klasser"

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service-gui#63]
For å gjenskape:
Stå i følgende skjermbilde:
![image](https://user-images.githubusercontent.com/1702357/151868340-52022ab3-f16c-4c28-9a57-7551fba68fce.png)

Trykk "Generer klasser", kommer til følgende skjermbilde:
![image](https://user-images.githubusercontent.com/1702357/151868586-cf3d7316-8d25-4f24-a583-736fbf2c246a.png)

Forventer egentlig å stå i opprinnelig skjermbilde, men med klasser utfylt. Dvs slik:
![image](https://user-images.githubusercontent.com/1702357/151868697-4c82731d-8f5a-4470-a70a-8e9dc321f603.png)

**Comment by heming-langrenn** [comment]
Utført. Etter at rekkefølgen er satt blir bruker sendt tilbake til oversikten.
